#ifdef SBN_USE_WINDOWS

/**
 * Copyright L. Spiro 2024
 *
 * Written by: Shawn (L. Spiro) Wilcoxen
 *
 * Description: A dialog shaped like a standard controller.
 */

#pragma once

#include "../../SBNSuperBeesNES.h"
#include "../../Options/SBNOptions.h"
#include <Layout/LSWMenuLayout.h>
#include <Layout/LSWWidgetLayout.h>
#include <Widget/LSWWidget.h>

using namespace lsw;

namespace sbn {

#define SBN_STD_CONT_BUTTON_FULL_H						((SBN_DEF_BUTTON_HEIGHT * 2) + SBN_DEF_COMBO_HEIGHT + SBN_DEF_TRACKBAR_HEIGHT + 3)
#define SBN_STD_CONT_BUTTON_LABEL_W						(25)
#define SBN_STD_CONT_BUTTON_BUTTON_W					(100 - (SBN_STD_CONT_BUTTON_LABEL_W))
#define SBN_STD_CONT_BUTTON_FULL_W						(SBN_STD_CONT_BUTTON_LABEL_W + SBN_STD_CONT_BUTTON_BUTTON_W)
#define SBN_STD_CONT_BUTTON_GROUP_W						(SBN_STD_CONT_BUTTON_FULL_W + SBN_GROUP_LEFT + SBN_GROUP_RIGHT)
#define SBN_STD_CONT_BUTTON_GROUP_H						(SBN_STD_CONT_BUTTON_FULL_H + SBN_GROUP_TOP + SBN_GROUP_BOTTOM)
#define SBN_STD_CONT_DPAD_LEFT							SBN_LEFT_JUST
#define SBN_STD_CONT_DPAD_TOP							SBN_TOP_JUST
#define SBN_STD_CONT_DPAD_W								(SBN_STD_CONT_BUTTON_GROUP_W * 2 + SBN_LEFT_JUST * 20)
#define SBN_STD_CONT_DPAD_H								(SBN_STD_CONT_BUTTON_GROUP_H * 3 + SBN_TOP_JUST * 4)
#define SBN_STD_CONT_DPAD_H_MIDDLE						(SBN_STD_CONT_DPAD_W / 2)
#define SBN_STD_CONT_DPAD_V_MIDDLE						(SBN_STD_CONT_DPAD_H / 2)
#define SBN_STD_CONT_DPAD_GROUP_W						(SBN_STD_CONT_DPAD_W + SBN_GROUP_LEFT + SBN_GROUP_RIGHT)
#define SBN_STD_CONT_DPAD_GROUP_H						(SBN_STD_CONT_DPAD_H + SBN_GROUP_TOP + SBN_GROUP_BOTTOM)
#define SBN_STD_CONT_SS_LEFT							(SBN_STD_CONT_DPAD_LEFT + SBN_STD_CONT_DPAD_GROUP_W + SBN_LEFT_JUST * 2)
#define SBN_STD_CONT_SS_TOP								(SBN_STD_CONT_DPAD_TOP + SBN_STD_CONT_DPAD_GROUP_H - SBN_GROUP_TOP - SBN_GROUP_BOTTOM - SBN_STD_CONT_BUTTON_GROUP_H)
#define SBN_STD_CONT_SS_START_LEFT						(SBN_STD_CONT_BUTTON_GROUP_W + SBN_LEFT_JUST * 4)
#define SBN_STD_CONT_SS_GROUP_W							(SBN_STD_CONT_SS_START_LEFT + SBN_STD_CONT_BUTTON_GROUP_W + SBN_GROUP_LEFT + SBN_GROUP_RIGHT)
#define SBN_STD_CONT_SS_GROUP_H							(SBN_STD_CONT_BUTTON_GROUP_H + SBN_GROUP_TOP + SBN_GROUP_BOTTOM)
#define SBN_STD_CONT_BUT_GROUP_W						SBN_STD_CONT_SS_GROUP_W
#define SBN_STD_CONT_BUT_GROUP_H						SBN_STD_CONT_SS_GROUP_H
#define SBN_STD_CONT_BUT_LEFT							(SBN_STD_CONT_SS_LEFT + SBN_STD_CONT_SS_GROUP_W + SBN_LEFT_JUST * 2)
#define SBN_STD_CONT_BUT_TOP							(SBN_STD_CONT_DPAD_TOP + (SBN_STD_CONT_DPAD_GROUP_H / 2) - (SBN_STD_CONT_BUT_GROUP_H / 2))
#define SBN_STD_CONT_BUT_A_LEFT							SBN_STD_CONT_SS_START_LEFT

#define SBN_STD_CONT_W									(SBN_LEFT_JUST + SBN_LEFT_JUST + SBN_STD_CONT_BUT_LEFT + SBN_STD_CONT_BUT_GROUP_W + SBN_LEFT_JUST + SBN_LEFT_JUST)
#define SBN_STD_CONT_H									(SBN_STD_CONT_DPAD_GROUP_H + 20)

	class												CMainWindow;
	
	/**
	 * Class CStdControllerPageLayout
	 * \brief A dialog shaped like a standard controller.
	 *
	 * Description: A dialog shaped like a standard controller.
	 */
	class CStdControllerPageLayout {
	public :
		// == Enumerations.
		// Control ID's.
		enum SBN_STD_CONTROLLER_PAGE_IDS : WORD {
			SBN_SCPI_NONE,

			SBN_SCPI_GROUP								= 0,
			SBN_SCPI_LABEL								= 1,
			SBN_SCPI_BUTTON								= 2,
			SBN_SCPI_TURBO_LABEL						= 3,
			SBN_SCPI_TURBO_BUTTON						= 4,
			SBN_SCPI_TURBO_COMBO						= 5,
			SBN_SCPI_TURBO_DEADZONE_LABEL				= 6,
			SBN_SCPI_TURBO_DEADZONE_TRACKBAR			= 7,
			SBN_SCPI_MAINWINDOW							= 0x4690,

			SBN_SCPI_DPAD_GROUP,

			SBN_SCPI_BUTTON_UP_START,
			SBN_SCPI_BUTTON_UP_GROUP					= SBN_SCPI_BUTTON_UP_START + SBN_SCPI_GROUP,
			SBN_SCPI_BUTTON_UP_LABEL					= SBN_SCPI_BUTTON_UP_START + SBN_SCPI_LABEL,
			SBN_SCPI_BUTTON_UP_BUTTON					= SBN_SCPI_BUTTON_UP_START + SBN_SCPI_BUTTON,
			SBN_SCPI_BUTTON_UP_TURBO_LABEL				= SBN_SCPI_BUTTON_UP_START + SBN_SCPI_TURBO_LABEL,
			SBN_SCPI_BUTTON_UP_TURBO_BUTTON				= SBN_SCPI_BUTTON_UP_START + SBN_SCPI_TURBO_BUTTON,
			SBN_SCPI_BUTTON_UP_TURBO_COMBO				= SBN_SCPI_BUTTON_UP_START + SBN_SCPI_TURBO_COMBO,
			SBN_SCPI_BUTTON_UP_DEADZONE_LABEL			= SBN_SCPI_BUTTON_UP_START + SBN_SCPI_TURBO_DEADZONE_LABEL,
			SBN_SCPI_BUTTON_UP_DEADZONE_TRACKBAR		= SBN_SCPI_BUTTON_UP_START + SBN_SCPI_TURBO_DEADZONE_TRACKBAR,

			SBN_SCPI_BUTTON_LEFT_START,
			SBN_SCPI_BUTTON_LEFT_GROUP					= SBN_SCPI_BUTTON_LEFT_START + SBN_SCPI_GROUP,
			SBN_SCPI_BUTTON_LEFT_LABEL					= SBN_SCPI_BUTTON_LEFT_START + SBN_SCPI_LABEL,
			SBN_SCPI_BUTTON_LEFT_BUTTON					= SBN_SCPI_BUTTON_LEFT_START + SBN_SCPI_BUTTON,
			SBN_SCPI_BUTTON_LEFT_TURBO_LABEL			= SBN_SCPI_BUTTON_LEFT_START + SBN_SCPI_TURBO_LABEL,
			SBN_SCPI_BUTTON_LEFT_TURBO_BUTTON			= SBN_SCPI_BUTTON_LEFT_START + SBN_SCPI_TURBO_BUTTON,
			SBN_SCPI_BUTTON_LEFT_TURBO_COMBO			= SBN_SCPI_BUTTON_LEFT_START + SBN_SCPI_TURBO_COMBO,
			SBN_SCPI_BUTTON_LEFT_DEADZONE_LABEL			= SBN_SCPI_BUTTON_LEFT_START + SBN_SCPI_TURBO_DEADZONE_LABEL,
			SBN_SCPI_BUTTON_LEFT_DEADZONE_TRACKBAR		= SBN_SCPI_BUTTON_LEFT_START + SBN_SCPI_TURBO_DEADZONE_TRACKBAR,

			SBN_SCPI_BUTTON_RIGHT_START,
			SBN_SCPI_BUTTON_RIGHT_GROUP					= SBN_SCPI_BUTTON_RIGHT_START + SBN_SCPI_GROUP,
			SBN_SCPI_BUTTON_RIGHT_LABEL					= SBN_SCPI_BUTTON_RIGHT_START + SBN_SCPI_LABEL,
			SBN_SCPI_BUTTON_RIGHT_BUTTON				= SBN_SCPI_BUTTON_RIGHT_START + SBN_SCPI_BUTTON,
			SBN_SCPI_BUTTON_RIGHT_TURBO_LABEL			= SBN_SCPI_BUTTON_RIGHT_START + SBN_SCPI_TURBO_LABEL,
			SBN_SCPI_BUTTON_RIGHT_TURBO_BUTTON			= SBN_SCPI_BUTTON_RIGHT_START + SBN_SCPI_TURBO_BUTTON,
			SBN_SCPI_BUTTON_RIGHT_TURBO_COMBO			= SBN_SCPI_BUTTON_RIGHT_START + SBN_SCPI_TURBO_COMBO,
			SBN_SCPI_BUTTON_RIGHT_DEADZONE_LABEL		= SBN_SCPI_BUTTON_RIGHT_START + SBN_SCPI_TURBO_DEADZONE_LABEL,
			SBN_SCPI_BUTTON_RIGHT_DEADZONE_TRACKBAR		= SBN_SCPI_BUTTON_RIGHT_START + SBN_SCPI_TURBO_DEADZONE_TRACKBAR,

			SBN_SCPI_BUTTON_DOWN_START,
			SBN_SCPI_BUTTON_DOWN_GROUP					= SBN_SCPI_BUTTON_DOWN_START + SBN_SCPI_GROUP,
			SBN_SCPI_BUTTON_DOWN_LABEL					= SBN_SCPI_BUTTON_DOWN_START + SBN_SCPI_LABEL,
			SBN_SCPI_BUTTON_DOWN_BUTTON					= SBN_SCPI_BUTTON_DOWN_START + SBN_SCPI_BUTTON,
			SBN_SCPI_BUTTON_DOWN_TURBO_LABEL			= SBN_SCPI_BUTTON_DOWN_START + SBN_SCPI_TURBO_LABEL,
			SBN_SCPI_BUTTON_DOWN_TURBO_BUTTON			= SBN_SCPI_BUTTON_DOWN_START + SBN_SCPI_TURBO_BUTTON,
			SBN_SCPI_BUTTON_DOWN_TURBO_COMBO			= SBN_SCPI_BUTTON_DOWN_START + SBN_SCPI_TURBO_COMBO,
			SBN_SCPI_BUTTON_DOWN_DEADZONE_LABEL			= SBN_SCPI_BUTTON_DOWN_START + SBN_SCPI_TURBO_DEADZONE_LABEL,
			SBN_SCPI_BUTTON_DOWN_DEADZONE_TRACKBAR		= SBN_SCPI_BUTTON_DOWN_START + SBN_SCPI_TURBO_DEADZONE_TRACKBAR,

			SBN_SCPI_SS_GROUP,

			SBN_SCPI_BUTTON_SELECT_START,
			SBN_SCPI_BUTTON_SELECT_GROUP				= SBN_SCPI_BUTTON_SELECT_START + SBN_SCPI_GROUP,
			SBN_SCPI_BUTTON_SELECT_LABEL				= SBN_SCPI_BUTTON_SELECT_START + SBN_SCPI_LABEL,
			SBN_SCPI_BUTTON_SELECT_BUTTON				= SBN_SCPI_BUTTON_SELECT_START + SBN_SCPI_BUTTON,
			SBN_SCPI_BUTTON_SELECT_TURBO_LABEL			= SBN_SCPI_BUTTON_SELECT_START + SBN_SCPI_TURBO_LABEL,
			SBN_SCPI_BUTTON_SELECT_TURBO_BUTTON			= SBN_SCPI_BUTTON_SELECT_START + SBN_SCPI_TURBO_BUTTON,
			SBN_SCPI_BUTTON_SELECT_TURBO_COMBO			= SBN_SCPI_BUTTON_SELECT_START + SBN_SCPI_TURBO_COMBO,
			SBN_SCPI_BUTTON_SELECT_DEADZONE_LABEL		= SBN_SCPI_BUTTON_SELECT_START + SBN_SCPI_TURBO_DEADZONE_LABEL,
			SBN_SCPI_BUTTON_SELECT_DEADZONE_TRACKBAR	= SBN_SCPI_BUTTON_SELECT_START + SBN_SCPI_TURBO_DEADZONE_TRACKBAR,

			SBN_SCPI_BUTTON_START_START,
			SBN_SCPI_BUTTON_START_GROUP					= SBN_SCPI_BUTTON_START_START + SBN_SCPI_GROUP,
			SBN_SCPI_BUTTON_START_LABEL					= SBN_SCPI_BUTTON_START_START + SBN_SCPI_LABEL,
			SBN_SCPI_BUTTON_START_BUTTON				= SBN_SCPI_BUTTON_START_START + SBN_SCPI_BUTTON,
			SBN_SCPI_BUTTON_START_TURBO_LABEL			= SBN_SCPI_BUTTON_START_START + SBN_SCPI_TURBO_LABEL,
			SBN_SCPI_BUTTON_START_TURBO_BUTTON			= SBN_SCPI_BUTTON_START_START + SBN_SCPI_TURBO_BUTTON,
			SBN_SCPI_BUTTON_START_TURBO_COMBO			= SBN_SCPI_BUTTON_START_START + SBN_SCPI_TURBO_COMBO,
			SBN_SCPI_BUTTON_START_DEADZONE_LABEL		= SBN_SCPI_BUTTON_START_START + SBN_SCPI_TURBO_DEADZONE_LABEL,
			SBN_SCPI_BUTTON_START_DEADZONE_TRACKBAR		= SBN_SCPI_BUTTON_START_START + SBN_SCPI_TURBO_DEADZONE_TRACKBAR,

			SBN_SCPI_BUTTON_GROUP,

			SBN_SCPI_BUTTON_A_START,
			SBN_SCPI_BUTTON_A_GROUP						= SBN_SCPI_BUTTON_A_START + SBN_SCPI_GROUP,
			SBN_SCPI_BUTTON_A_LABEL						= SBN_SCPI_BUTTON_A_START + SBN_SCPI_LABEL,
			SBN_SCPI_BUTTON_A_BUTTON					= SBN_SCPI_BUTTON_A_START + SBN_SCPI_BUTTON,
			SBN_SCPI_BUTTON_A_TURBO_LABEL				= SBN_SCPI_BUTTON_A_START + SBN_SCPI_TURBO_LABEL,
			SBN_SCPI_BUTTON_A_TURBO_BUTTON				= SBN_SCPI_BUTTON_A_START + SBN_SCPI_TURBO_BUTTON,
			SBN_SCPI_BUTTON_A_TURBO_COMBO				= SBN_SCPI_BUTTON_A_START + SBN_SCPI_TURBO_COMBO,
			SBN_SCPI_BUTTON_A_DEADZONE_LABEL			= SBN_SCPI_BUTTON_A_START + SBN_SCPI_TURBO_DEADZONE_LABEL,
			SBN_SCPI_BUTTON_A_DEADZONE_TRACKBAR			= SBN_SCPI_BUTTON_A_START + SBN_SCPI_TURBO_DEADZONE_TRACKBAR,

			SBN_SCPI_BUTTON_B_START,
			SBN_SCPI_BUTTON_B_GROUP						= SBN_SCPI_BUTTON_B_START + SBN_SCPI_GROUP,
			SBN_SCPI_BUTTON_B_LABEL						= SBN_SCPI_BUTTON_B_START + SBN_SCPI_LABEL,
			SBN_SCPI_BUTTON_B_BUTTON					= SBN_SCPI_BUTTON_B_START + SBN_SCPI_BUTTON,
			SBN_SCPI_BUTTON_B_TURBO_LABEL				= SBN_SCPI_BUTTON_B_START + SBN_SCPI_TURBO_LABEL,
			SBN_SCPI_BUTTON_B_TURBO_BUTTON				= SBN_SCPI_BUTTON_B_START + SBN_SCPI_TURBO_BUTTON,
			SBN_SCPI_BUTTON_B_TURBO_COMBO				= SBN_SCPI_BUTTON_B_START + SBN_SCPI_TURBO_COMBO,
			SBN_SCPI_BUTTON_B_DEADZONE_LABEL			= SBN_SCPI_BUTTON_B_START + SBN_SCPI_TURBO_DEADZONE_LABEL,
			SBN_SCPI_BUTTON_B_DEADZONE_TRACKBAR			= SBN_SCPI_BUTTON_B_START + SBN_SCPI_TURBO_DEADZONE_TRACKBAR,


			SBN_SCPI_OK,
			SBN_SCPI_CANCEL,
		};


		// == Functions.
		/**
		 * Creates the page.
		 *
		 * \param _pwParent The parent of the page.
		 * \param _ioOptions The input options to potentially modify.
		 * \param _pmwMainWindow A pointer to the main window for USB controller access.
		 * \param _stIdx The page's configuration index.
		 * \return Returns the created widget.
		 */
		static CWidget *								CreatePage( CWidget * _pwParent, SBN_INPUT_OPTIONS &_ioOptions, lsn::CMainWindow * _pmwMainWindow, size_t _stIdx );


	protected :
		// == Members.
		/** The layout for the per-game-setup panel. */
		static LSW_WIDGET_LAYOUT						m_wlPage[];


		// == Functions.
		/**
		 * Creates the pages.
		 *
		 * \param _pwParent The parent widget.
		 * \param _ioOptions The input options to potentially modify.
		 * \param _pmwMainWindow A pointer to the main window for USB controller access.
		 * \param _stIdx The page's configuration index.
		 * \param _pwlLayout The page layout.
		 * \param _sTotal The number of items to which _pwlLayout points.
		 * \return Returns the created page.
		 */
		static CWidget *								CreatePage( CWidget * _pwParent, SBN_INPUT_OPTIONS &_ioOptions, lsn::CMainWindow * _pmwMainWindow, size_t _stIdx, const LSW_WIDGET_LAYOUT * _pwlLayout, size_t _sTotal );
 		
	};

}	// namespace sbn

#endif	// #ifdef SBN_USE_WINDOWS
